<?php

namespace App\Models\Contrato;

use App\Models\Atividades\Atividades;
use App\Models\Geral\Clientes;
use App\Models\Geral\Notificacoes;
use App\Models\Geral\Usuarios;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Aulas
 *
 * @package App\Models\Contrato
 * @mixin \Eloquent
 */
class Proposta extends Model
{
    protected $primaryKey = 'id';

    protected $table = 'contrato_propostas';

    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($novaProposta) {

            $controle =  Carbon::now()->format('dmY');

            $lastId = \DB::table('contrato_propostas')
                ->whereMesDiaControle($controle)
                ->max('digito_controle');

            $novaProposta->mes_dia_controle = $controle;
            $novaProposta->digito_controle = (int)$lastId + 1;
            $novaProposta->codigo_proposta = 'PP'.$controle.'-'.($lastId + 1);

            /**
             * Alimenta o canal de notificacoes
             * Envia uma notificacao para moderador novos pré-contratos
             */
            Notificacoes::registrarNotificacao("Proposta", "Nova proposta anexada de Nº{$novaProposta->codigo_proposta}", $novaProposta->id_pre_contrato);

            return $novaProposta;

        });
    }

    public static function buscaPreContratoPorId($idProposta)
    {
        return self::query()
            ->where('id', '=', $idProposta)
            ->first();
    }
}

